apiVersion: v1
kind: PersistentVolume
metadata:
  name: $CONTACTS_PV
spec:
  volumeMode: Filesystem
  accessModes:
    - ReadWriteOnce
  capacity:
    storage: 400Mi
  storageClassName: $CONTACTS_STORAGE
  hostPath:
    path: /data/volumes/contacts-pv   # Where all the hard drives are mounted
    type: DirectoryOrCreate