apiVersion: v1
kind: PersistentVolume
metadata:
  name: $DOCSTORE_PV
spec:
  volumeMode: Filesystem
  accessModes:
    - ReadWriteOnce
  capacity:
    storage: 400Mi
  storageClassName: $DOCSTORE_STORAGE
  hostPath:
    path: /data/volumes/docstore-pv   # Where all the hard drives are mounted
    type: DirectoryOrCreate