apiVersion: v1
kind: PersistentVolume
metadata:
  name: $FILESTORE_PV
spec:
  volumeMode: Filesystem
  accessModes:
    - ReadWriteOnce
  capacity:
    storage: 400Mi
  storageClassName: $FILESTORE_STORAGE
  hostPath:
    path: /data/volumes/filestore-pv   # Where all the hard drives are mounted
    type: DirectoryOrCreate