apiVersion: v1
kind: PersistentVolume
metadata:
  name: $MONGO_PV
spec:
  volumeMode: Filesystem
  accessModes:
    - ReadWriteOnce
  capacity:
    storage: 500Mi
  storageClassName: $MONGO_STORAGE
  hostPath:
    path: /data/volumes/mongo-pv   # Where all the hard drives are mounted
    type: DirectoryOrCreate