apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: notifications-claim0
spec:
  accessModes:
    - ReadWriteOnce
  storageClassName: $NOTIFICATIONS_STORAGE
  resources:
    requests:
      storage: 100Mi