apiVersion: v1
kind: PersistentVolume
metadata:
  name: $NOTIFICATIONS_PV
spec:
  volumeMode: Filesystem
  accessModes:
    - ReadWriteOnce
  capacity:
    storage: 100Mi
  storageClassName: $NOTIFICATIONS_STORAGE
  hostPath:
    path: /data/volumes/notifications-pv   # Where all the hard drives are mounted
    type: DirectoryOrCreate