apiVersion: v1
kind: PersistentVolume
metadata:
  name: $SPELLING_PV
spec:
  volumeMode: Filesystem
  accessModes:
    - ReadWriteOnce
  capacity:
    storage: 100Mi
  storageClassName: $SPELLING_STORAGE
  hostPath:
    path: /data/volumes/spelling-pv   # Where all the hard drives are mounted
    type: DirectoryOrCreate