apiVersion: v1
kind: PersistentVolume
metadata:
  name: $TAGS_PV
spec:
  volumeMode: Filesystem
  accessModes:
    - ReadWriteOnce
  capacity:
    storage: 100Mi
  storageClassName: $TAGS_STORAGE
  hostPath:
    path: /data/volumes/tags-pv   # Where all the hard drives are mounted
    type: DirectoryOrCreate